name: Release Firefox XPI

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  build-and-sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create extension zip
        run: |
          mkdir -p artifact
          zip -r artifact/extension.zip . -x "*.git*"

      - name: Sign Firefox Extension (XPI)
        uses: cardinalby/webext-buildtools-firefox-sign-xpi-action@1.0.6
        with:
          timeoutMs: 600000
          zipFilePath: artifact/extension.zip
          xpiFilePath: artifact/extension.signed.xpi
          extensionId: ${{ secrets.FF_EXT_UUID }}
          jwtIssuer: ${{ secrets.FF_JWT_ISSUER }}
          jwtSecret: ${{ secrets.FF_JWT_SECRET }}

      - name: Upload Signed XPI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-xpi
          path: artifact/extension.signed.xpi

      - name: Get version from manifest.json
        id: get_version
        run: echo "version=$(jq -r '.version' manifest.json)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifact/extension.signed.xpi
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: "Release v${{ steps.get_version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
